# Houve conflitos entre os agentes? Como o orquestrador poderia resolvê-los?

Em um sistema com oito agentes especializados, os "conflitos" são inerentes e surgem como **tensões de foco** ou **divergências de critério**. O **Coordenador Pedagógico – Luis** (atuando como Orquestrador) é o principal responsável por gerenciar essas tensões através de um fluxo de trabalho bem definido.

| Categoria de Conflito | Conflitos Observados | Causa Provável | Estratégia do Orquestrador (Luis) para Resolução |
| --- | --- | --- | --- |
| **Tensão de Critério** | Divergência entre a **avaliação de falhas** de Erika (Diagnóstico) e a **avaliação de domínio** de Julio (Avaliação). | Erika foca no que falta para começar, Julio foca no que foi dominado para avançar. Ambos são avaliativos, mas com objetivos diferentes. | **Sequenciamento e Propósito:** Luis garante que o diagnóstico de Erika ocorra **antes** do conteúdo e que a avaliação de Julio ocorra **após** a prática. O propósito de cada um é claro e sequencial, evitando sobreposição. |
| **Tensão Pedagógica** | Divergência entre a **exigência prática** de Sena (Exercícios) e o **apoio emocional** de Micael (Motivacional). | Sena exige desempenho e fixação, o que pode gerar frustração. Micael exige bem-estar e engajamento. | **Regra de Intervenção:** Luis estabelece que a intervenção de Micael é um **passo obrigatório** após uma falha ou dificuldade relatada no exercício de Sena, transformando a falha em um ciclo de resiliência. |
| **Tensão de Escopo** | O Tutor Tiago pode focar em um conceito, mas o Agente Pedro (Estratégias) pode sugerir uma rotina que **não prioriza** o estudo desse conceito. | Tiago foca no *o quê* (conteúdo), Pedro foca no *como* (método). | **Alinhamento Contextual:** Luis deve garantir que a orientação de Pedro seja **contextualizada** com o plano de estudos atual. A rotina sugerida deve priorizar o conteúdo que Tiago e Sena estão trabalhando. |
| **Tensão de Informação** | O Agente Jonathan (Relatório) pode consolidar dados, mas o Coordenador Luis pode precisar de uma **informação específica** para tomar uma decisão de encaminhamento. | Jonathan foca na visão geral e no histórico, Luis foca na decisão imediata. | **Comunicação Direta:** Luis, como Orquestrador, deve ter a prerrogativa de fazer **perguntas curtas e objetivas** a Jonathan, exigindo dados específicos para a tomada de decisão, em vez de depender apenas do relatório final. |

Em resumo, o **Coordenador Pedagógico – Luis** atua como o **gestor do fluxo**, utilizando o **sequenciamento estrito** e a **definição clara de *****triggers*** (gatilhos de ação) para garantir que as diferentes especializações dos agentes trabalhem em sinergia para o sucesso do aluno. O foco em **perguntas curtas e objetivas** nos *prompts* de todos os agentes é a principal ferramenta para manter a coordenação ágil.

